services:

  # Base de données MongoDB
  mongodb:
    image: mongo:7.0
    container_name: blogpress-mongodb
    environment:
      MONGO_INITDB_DATABASE: blogpress
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty87
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - blogpress-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mon application Spring Boot
  aapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogpress-api-app
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_MONGODB_URI=mongodb://root:qwerty87@mongodb:27017/blogpress?authSource=admin
      - JWT_SECRET=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIHNlY3JldCBrZXkgZm9yIEJsb2dwcmVzcyBBUEkgMjAyNQ==
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - blogpress-network
    volumes:
      - app-uploads:/app/uploads

volumes:
  mongodb-data:
    driver: local
  app-uploads:
    driver: local

networks:
  blogpress-network:
    driver: bridge