# Nom de l'application
spring.application.name=blogpress-api

# Configuration commune
server.port=8090

# Profil actif (dev par défaut)
spring.profiles.active=dev

# ==========================================
# PROFIL DEV (Développement local)
# ==========================================
spring.data.mongodb.uri=mongodb://root:qwerty87@localhost:27017/blogpress?authSource=admin
spring.data.mongodb.auto-index-creation=true

# Logs en dev
logging.level.org.springframework.data.mongodb=DEBUG

# ==========================================
# PROFIL PROD (Production avec Atlas)
# ==========================================
# À activer en production avec --spring.profiles.active=prod