# Configuration MongoDB Atlas pour la production
spring.data.mongodb.uri=${MONGODB_ATLAS_URI}

# Logs en production
logging.level.org.springframework.data.mongodb=INFO
logging.level.root=WARN


# Définir la variable d'environnement avec ta vraie connection string Atlas
# export MONGODB_ATLAS_URI="mongodb+srv://user:password@cluster0.xxxxx.mongodb.net/mydatabase"

# Lancer l'app avec le profil prod
#java -jar blogpress-api.jar --spring.profiles.active=prod